/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { Block } from '@src/components/game/Block.tsx';

type GLTFResult = GLTF & {
  nodes: {
    Bottom: THREE.Mesh;
    [x: string]: THREE.Mesh;
  };
  materials: {
    BoardBottom: THREE.MeshStandardMaterial;
    BlockMaterial: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./3D/board-v1.0.glb') as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <mesh
        name="Bottom"
        castShadow
        receiveShadow
        geometry={nodes.Bottom.geometry}
        material={materials.BoardBottom}
        position={[0.02, -0.0133, -0.0123]}
      />
      <Block
        name="Cube001"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        position={[-3.9543, 0.1184, 3.8014]}
      />
      <Block
        name="Cube002"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube002.material}
        position={[-2.966, 0.1184, 3.8014]}
      />
      <Block
        name="Cube003"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube003.material}
        position={[-1.9778, 0.1184, 3.8014]}
      />
      <Block
        name="Cube004"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube004.material}
        position={[-0.9895, 0.1184, 3.8014]}
      />
      <Block
        name="Cube005"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube005.material}
        position={[-0.0012, 0.1184, 3.8014]}
      />
      <Block
        name="Cube006"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube006.material}
        position={[0.987, 0.1184, 3.8014]}
      />
      <Block
        name="Cube007"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube007.material}
        position={[1.9753, 0.1184, 3.8014]}
      />
      <Block
        name="Cube008"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube008.material}
        position={[2.9636, 0.1184, 3.8014]}
      />
      <Block
        name="Cube009"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube009.material}
        position={[3.9518, 0.1184, 3.8014]}
      />
      <Block
        name="Cube010"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube010.material}
        position={[-3.9543, 0.1184, 2.8526]}
      />
      <Block
        name="Cube011"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube011.material}
        position={[-2.966, 0.1184, 2.8526]}
      />
      <Block
        name="Cube012"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube012.material}
        position={[-1.9778, 0.1184, 2.8526]}
      />
      <Block
        name="Cube013"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube013.material}
        position={[-0.9895, 0.1184, 2.8526]}
      />
      <Block
        name="Cube014"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube014.material}
        position={[-0.0012, 0.1184, 2.8526]}
      />
      <Block
        name="Cube015"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube015.material}
        position={[0.987, 0.1184, 2.8526]}
      />
      <Block
        name="Cube016"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube016.material}
        position={[1.9753, 0.1184, 2.8526]}
      />
      <Block
        name="Cube017"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube017.material}
        position={[2.9636, 0.1184, 2.8526]}
      />
      <Block
        name="Cube018"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube018.material}
        position={[3.9518, 0.1184, 2.8526]}
      />
      <Block
        name="Cube019"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube019.material}
        position={[-3.9543, 0.1184, 1.9038]}
      />
      <Block
        name="Cube020"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube020.material}
        position={[-2.966, 0.1184, 1.9038]}
      />
      <Block
        name="Cube021"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube021.material}
        position={[-1.9778, 0.1184, 1.9038]}
      />
      <Block
        name="Cube022"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube022.material}
        position={[-0.9895, 0.1184, 1.9038]}
      />
      <Block
        name="Cube023"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube023.material}
        position={[-0.0012, 0.1184, 1.9038]}
      />
      <Block
        name="Cube024"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube024.material}
        position={[0.987, 0.1184, 1.9038]}
      />
      <Block
        name="Cube025"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube025.material}
        position={[1.9753, 0.1184, 1.9038]}
      />
      <Block
        name="Cube026"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube026.material}
        position={[2.9636, 0.1184, 1.9038]}
      />
      <Block
        name="Cube027"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube027.material}
        position={[3.9518, 0.1184, 1.9038]}
      />
      <Block
        name="Cube028"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube028.material}
        position={[-3.9543, 0.1184, 0.955]}
      />
      <Block
        name="Cube029"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube029.material}
        position={[-2.966, 0.1184, 0.955]}
      />
      <Block
        name="Cube030"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube030.material}
        position={[-1.9778, 0.1184, 0.955]}
      />
      <Block
        name="Cube031"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube031.material}
        position={[-0.9895, 0.1184, 0.955]}
      />
      <Block
        name="Cube032"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube032.material}
        position={[-0.0012, 0.1184, 0.955]}
      />
      <Block
        name="Cube033"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube033.material}
        position={[0.987, 0.1184, 0.955]}
      />
      <Block
        name="Cube034"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube034.material}
        position={[1.9753, 0.1184, 0.955]}
      />
      <Block
        name="Cube035"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube035.material}
        position={[2.9636, 0.1184, 0.955]}
      />
      <Block
        name="Cube036"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube036.material}
        position={[3.9518, 0.1184, 0.955]}
      />
      <Block
        name="Cube037"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube037.material}
        position={[-3.9543, 0.1184, 0.0061]}
      />
      <Block
        name="Cube038"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube038.material}
        position={[-2.966, 0.1184, 0.0061]}
      />
      <Block
        name="Cube039"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube039.material}
        position={[-1.9778, 0.1184, 0.0061]}
      />
      <Block
        name="Cube040"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube040.material}
        position={[-0.9895, 0.1184, 0.0061]}
      />
      <Block
        name="Cube041"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube041.material}
        position={[-0.0012, 0.1184, 0.0061]}
      />
      <Block
        name="Cube042"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube042.material}
        position={[0.987, 0.1184, 0.0061]}
      />
      <Block
        name="Cube043"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube043.material}
        position={[1.9753, 0.1184, 0.0061]}
      />
      <Block
        name="Cube044"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube044.material}
        position={[2.9636, 0.1184, 0.0061]}
      />
      <Block
        name="Cube045"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube045.material}
        position={[3.9518, 0.1184, 0.0061]}
      />
      <Block
        name="Cube046"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube046.material}
        position={[-3.9543, 0.1184, -0.9427]}
      />
      <Block
        name="Cube047"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube047.material}
        position={[-2.966, 0.1184, -0.9427]}
      />
      <Block
        name="Cube048"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube048.material}
        position={[-1.9778, 0.1184, -0.9427]}
      />
      <Block
        name="Cube049"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube049.material}
        position={[-0.9895, 0.1184, -0.9427]}
      />
      <Block
        name="Cube050"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube050.material}
        position={[-0.0012, 0.1184, -0.9427]}
      />
      <Block
        name="Cube051"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube051.material}
        position={[0.987, 0.1184, -0.9427]}
      />
      <Block
        name="Cube052"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube052.material}
        position={[1.9753, 0.1184, -0.9427]}
      />
      <Block
        name="Cube053"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube053.material}
        position={[2.9636, 0.1184, -0.9427]}
      />
      <Block
        name="Cube054"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube054.material}
        position={[3.9518, 0.1184, -0.9427]}
      />
      <Block
        name="Cube055"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube055.material}
        position={[-3.9543, 0.1184, -1.8915]}
      />
      <Block
        name="Cube056"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube056.material}
        position={[-2.966, 0.1184, -1.8915]}
      />
      <Block
        name="Cube057"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube057.material}
        position={[-1.9778, 0.1184, -1.8915]}
      />
      <Block
        name="Cube058"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube058.material}
        position={[-0.9895, 0.1184, -1.8915]}
      />
      <Block
        name="Cube059"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube059.material}
        position={[-0.0012, 0.1184, -1.8915]}
      />
      <Block
        name="Cube060"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube060.material}
        position={[0.987, 0.1184, -1.8915]}
      />
      <Block
        name="Cube061"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube061.material}
        position={[1.9753, 0.1184, -1.8915]}
      />
      <Block
        name="Cube062"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube062.material}
        position={[2.9636, 0.1184, -1.8915]}
      />
      <Block
        name="Cube063"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube063.material}
        position={[3.9518, 0.1184, -1.8915]}
      />
      <Block
        name="Cube064"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube064.material}
        position={[-3.9543, 0.1184, -2.8403]}
      />
      <Block
        name="Cube065"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube065.material}
        position={[-2.966, 0.1184, -2.8403]}
      />
      <Block
        name="Cube066"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube066.material}
        position={[-1.9778, 0.1184, -2.8403]}
      />
      <Block
        name="Cube067"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube067.material}
        position={[-0.9895, 0.1184, -2.8403]}
      />
      <Block
        name="Cube068"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube068.material}
        position={[-0.0012, 0.1184, -2.8403]}
      />
      <Block
        name="Cube069"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube069.material}
        position={[0.987, 0.1184, -2.8403]}
      />
      <Block
        name="Cube070"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube070.material}
        position={[1.9753, 0.1184, -2.8403]}
      />
      <Block
        name="Cube071"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube071.material}
        position={[2.9636, 0.1184, -2.8403]}
      />
      <Block
        name="Cube072"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube072.material}
        position={[3.9518, 0.1184, -2.8403]}
      />
      <Block
        name="Cube073"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube073.material}
        position={[-3.9543, 0.1184, -3.7892]}
      />
      <Block
        name="Cube074"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube074.material}
        position={[-2.966, 0.1184, -3.7892]}
      />
      <Block
        name="Cube075"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube075.material}
        position={[-1.9778, 0.1184, -3.7892]}
      />
      <Block
        name="Cube076"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube076.material}
        position={[-0.9895, 0.1184, -3.7892]}
      />
      <Block
        name="Cube077"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube077.material}
        position={[-0.0012, 0.1184, -3.7892]}
      />
      <Block
        name="Cube078"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube078.material}
        position={[0.987, 0.1184, -3.7892]}
      />
      <Block
        name="Cube079"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube079.material}
        position={[1.9753, 0.1184, -3.7892]}
      />
      <Block
        name="Cube080"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube080.material}
        position={[2.9636, 0.1184, -3.7892]}
      />
      <Block
        name="Cube081"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube081.material}
        position={[3.9518, 0.1184, -3.7892]}
      />
    </group>
  );
}

useGLTF.preload('./3D/board-v1.0.glb');
