name: Publish to GitHub Pages on Release

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Bun runtime
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.24 # or "latest", "canary", <sha>
      - name: Install dependencies
        run: bun install
      - name: Build static files
        run: bun run build:github
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
