name: Publish to GitHub with Versioning

on:
  release:
    types: [created]
    push:
      branches:
        - '*' # Match all branches to enable versioning for each branch
  pull_request:
    branches:
      - '*' # Also run on pull requests

jobs:
  comment-on-pr:
    needs: publish-review-version
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Comment on Pull Request
        id: commentLiveUrl
        uses: peter-evans/create-or-update-comment@v4
        with:
          edit-mode: replace
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Live view is available at [Live](https://n1md7.github.io/GG-Soft-Quoridor/${{ github.head_ref }}/)
      - name: Add reaction to comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          reactions: |
            rocket
            eyes
            heart
            hooray
          comment-id: ${{ steps.commentLiveUrl.outputs.comment-id }}

  publish-review-version:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Bun runtime
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.24 # or "latest", "canary", <sha>
      - name: Install dependencies
        run: bun install
      - name: Set VITE_RELEASE_VERSION Environment Variable
        run: |
          echo "VITE_RELEASE_VERSION=${{ github.head_ref }}/" >> $GITHUB_ENV
      - name: Build static files
        env:
          VITE_RELEASE_VERSION: ${{ env.VITE_RELEASE_VERSION }}
        run: bun run build:github
      - name: Set Publish Directory
        id: publish_dir
        run: |
          mkdir -p ${{ env.VITE_RELEASE_VERSION }}
          cp -R dist/* ${{ env.VITE_RELEASE_VERSION }}
          rm -rf dist
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          keep_files: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: github-static-files

  publish-release-version:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Bun runtime
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.24 # or "latest", "canary", <sha>
      - name: Install dependencies
        run: bun install
      - name: Set VITE_RELEASE_VERSION Environment Variable
        run: |
          echo "VITE_RELEASE_VERSION=${{ github.event.release.tag_name }}/" >> $GITHUB_ENV
      - name: Build static files
        env:
          VITE_RELEASE_VERSION: ${{ env.VITE_RELEASE_VERSION }}
          VITE_VERSION: ${{ env.VITE_RELEASE_VERSION }}
        run: bun run build:github
      - name: Copy files to release and root directory
        run: |
          mkdir -p ${{ env.VITE_RELEASE_VERSION }}
          cp -R dist/* ${{ env.VITE_RELEASE_VERSION }}
          cp -R dist/* ./
          rm -rf dist
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          keep_files: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: github-static-files
