name: Publish to GitHub with Versioning
description: Build and deploy static files to GitHub Pages with branch versioning. It will create a new directory for each branch and release.

on:
  release:
    types: [created]
    push:
      branches:
        - '*' # Match all branches to enable versioning for each branch
  pull_request:
    branches:
      - '*' # Also run on pull requests

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Comment on Pull Request
        id: commentLiveUrl
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          edit-mode: replace
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Live view is available at [Live](https://n1md7.github.io/GG-Soft-Quoridor/${{ github.head_ref }}/)
      - name: Add reaction to comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          reactions: [eyes, rocket]
          comment-id: ${{ steps.commentLiveUrl.outputs.comment-id }}

  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event_name == 'pull_request' }}
      - name: Use Bun runtime
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.24 # or "latest", "canary", <sha>
      - name: Install dependencies
        run: bun install
      - name: Set VITE_RELEASE_VERSION Environment Variable
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "VITE_RELEASE_VERSION=${{ github.event.release.tag_name }}/" >> $GITHUB_ENV
          else
            echo "VITE_RELEASE_VERSION=${{ github.head_ref }}/" >> $GITHUB_ENV
          fi
      - name: Build static files
        env:
          VITE_RELEASE_VERSION: ${{ env.VITE_RELEASE_VERSION }}
        run: bun run build:github
      - name: Set Publish Directory
        id: publish_dir
        run: |
          mv dist ${{ env.VITE_RELEASE_VERSION }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          keep_files: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: github-static-files
